// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: protofile/payment.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentResponse) Reset() {
	*x = PaymentResponse{}
	mi := &file_protofile_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentResponse) ProtoMessage() {}

func (x *PaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protofile_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentResponse.ProtoReflect.Descriptor instead.
func (*PaymentResponse) Descriptor() ([]byte, []int) {
	return file_protofile_payment_proto_rawDescGZIP(), []int{0}
}

type PaymentRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	CreditCard    *PaymentRequest_CreditCard `protobuf:"bytes,1,opt,name=creditCard,proto3" json:"creditCard,omitempty"`
	Amount        float64                    `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Store         string                     `protobuf:"bytes,3,opt,name=store,proto3" json:"store,omitempty"`
	Description   string                     `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentRequest) Reset() {
	*x = PaymentRequest{}
	mi := &file_protofile_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentRequest) ProtoMessage() {}

func (x *PaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protofile_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentRequest.ProtoReflect.Descriptor instead.
func (*PaymentRequest) Descriptor() ([]byte, []int) {
	return file_protofile_payment_proto_rawDescGZIP(), []int{1}
}

func (x *PaymentRequest) GetCreditCard() *PaymentRequest_CreditCard {
	if x != nil {
		return x.CreditCard
	}
	return nil
}

func (x *PaymentRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentRequest) GetStore() string {
	if x != nil {
		return x.Store
	}
	return ""
}

func (x *PaymentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type PaymentRequest_CreditCard struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Number          string                 `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	ExpirationMonth int32                  `protobuf:"varint,3,opt,name=expirationMonth,proto3" json:"expirationMonth,omitempty"`
	ExpirationYear  int32                  `protobuf:"varint,4,opt,name=expirationYear,proto3" json:"expirationYear,omitempty"`
	Cvv             int32                  `protobuf:"varint,5,opt,name=cvv,proto3" json:"cvv,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PaymentRequest_CreditCard) Reset() {
	*x = PaymentRequest_CreditCard{}
	mi := &file_protofile_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentRequest_CreditCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentRequest_CreditCard) ProtoMessage() {}

func (x *PaymentRequest_CreditCard) ProtoReflect() protoreflect.Message {
	mi := &file_protofile_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentRequest_CreditCard.ProtoReflect.Descriptor instead.
func (*PaymentRequest_CreditCard) Descriptor() ([]byte, []int) {
	return file_protofile_payment_proto_rawDescGZIP(), []int{1, 0}
}

func (x *PaymentRequest_CreditCard) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PaymentRequest_CreditCard) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *PaymentRequest_CreditCard) GetExpirationMonth() int32 {
	if x != nil {
		return x.ExpirationMonth
	}
	return 0
}

func (x *PaymentRequest_CreditCard) GetExpirationYear() int32 {
	if x != nil {
		return x.ExpirationYear
	}
	return 0
}

func (x *PaymentRequest_CreditCard) GetCvv() int32 {
	if x != nil {
		return x.Cvv
	}
	return 0
}

var File_protofile_payment_proto protoreflect.FileDescriptor

const file_protofile_payment_proto_rawDesc = "" +
	"\n" +
	"\x17protofile/payment.proto\x12\apayment\"\x11\n" +
	"\x0fPaymentResponse\"\xc3\x02\n" +
	"\x0ePaymentRequest\x12B\n" +
	"\n" +
	"creditCard\x18\x01 \x01(\v2\".payment.PaymentRequest.CreditCardR\n" +
	"creditCard\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x14\n" +
	"\x05store\x18\x03 \x01(\tR\x05store\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x1a\x9c\x01\n" +
	"\n" +
	"CreditCard\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06number\x18\x02 \x01(\tR\x06number\x12(\n" +
	"\x0fexpirationMonth\x18\x03 \x01(\x05R\x0fexpirationMonth\x12&\n" +
	"\x0eexpirationYear\x18\x04 \x01(\x05R\x0eexpirationYear\x12\x10\n" +
	"\x03cvv\x18\x05 \x01(\x05R\x03cvv2P\n" +
	"\x0ePaymentService\x12>\n" +
	"\aPayment\x12\x17.payment.PaymentRequest\x1a\x18.payment.PaymentResponse\"\x00B\tZ\agrpc/pbb\x06proto3"

var (
	file_protofile_payment_proto_rawDescOnce sync.Once
	file_protofile_payment_proto_rawDescData []byte
)

func file_protofile_payment_proto_rawDescGZIP() []byte {
	file_protofile_payment_proto_rawDescOnce.Do(func() {
		file_protofile_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protofile_payment_proto_rawDesc), len(file_protofile_payment_proto_rawDesc)))
	})
	return file_protofile_payment_proto_rawDescData
}

var file_protofile_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protofile_payment_proto_goTypes = []any{
	(*PaymentResponse)(nil),           // 0: payment.PaymentResponse
	(*PaymentRequest)(nil),            // 1: payment.PaymentRequest
	(*PaymentRequest_CreditCard)(nil), // 2: payment.PaymentRequest.CreditCard
}
var file_protofile_payment_proto_depIdxs = []int32{
	2, // 0: payment.PaymentRequest.creditCard:type_name -> payment.PaymentRequest.CreditCard
	1, // 1: payment.PaymentService.Payment:input_type -> payment.PaymentRequest
	0, // 2: payment.PaymentService.Payment:output_type -> payment.PaymentResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protofile_payment_proto_init() }
func file_protofile_payment_proto_init() {
	if File_protofile_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protofile_payment_proto_rawDesc), len(file_protofile_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protofile_payment_proto_goTypes,
		DependencyIndexes: file_protofile_payment_proto_depIdxs,
		MessageInfos:      file_protofile_payment_proto_msgTypes,
	}.Build()
	File_protofile_payment_proto = out.File
	file_protofile_payment_proto_goTypes = nil
	file_protofile_payment_proto_depIdxs = nil
}
